### ISSUE TITLE
Big ugly story with all possible task

### ISSUE THREAD

**Issue by csaba-demeter** [csaba-demeter/zenhub-example-inbox#3]
**Story**
As a SM I want to have a clear overview of whats needed for completing an end-to-end userstory as impediment so that I can create better stories with the PO and ensure higher transparency in tracking and higher quality in delivery.
 
**AC**
Full list of tasks in general: which sub-processes are required for creating software from an idea. 
Have this in a clear, trackable, implementable, deducted, step-by-step way which is easy to understand and follow for anyone involved in the production.

**TASKS**
_STAGE 1: Preparation_ 
(dependencies for Stage2)
 - [ ] Ideation and story creation
 - [ ] Concept creation / discussion & iteration (with visual prototypes if needed) having inputs from each team member, listening to all aspects before finalization --> story / backlog refinement (splitting, details, AC, tasks, forecasting and their refinement)
 - [ ] Concept Finalization = Story finalization (ready-stories;) 

Most stories, as base units of value+work will need: 
(these also needs to consider when estimating and sprint planning)

_STAGE 2: Application Design_
(dependencies for Stage3)
 - [ ] UI design, animation design
 - [ ] Architectural design 
 - [ ] Documentation / KB creation
 - [ ] Copywrite and translations for localized content

_STAGE 3A: Application Development - Backend_
 - [ ] Database tasks 
 - [ ] Server side logic (with handling possible errors and considering General agreements)
 - [ ] Protobuf - datamodel for server-client comm 
 - [ ] API endpoints for server-client comm (based on Protobuf) with a) mocked data for in-development, and b) real data for final testing
 - [ ] DevOps tasks for setting up / running the environment and 3rd party services/dependecies
 - [ ] Codebase Test-coverage
 - [ ] Codereview  and necessary fixes
 - [ ] Apply Content if needed 
 - [ ] Apply monitoring, logging triggers, params (performance-related, user-related, security-related, etc) 
 - [ ] Deployment 
 - [ ] Optimization tasks if needed

 _STAGE 3B: Application Development - Client-end (each platform)_
 - [ ] Layout creation (depending on UI design)
 - [ ] Animations (depending on Animation design)
 - [ ] Client-end logic: business and network, with handling possible errors (also depending on BE tasks); and considering General agreements) 
 - [ ] CodeReview
 - [ ] Documentation/codecomments (?)
 - [ ] Apply Localized content
 - [ ] Apply monitoring, logging triggers, params (performance-related, user-related, security-related, etc) 
 - [ ] UI/Instrument tests 

_STAGE 4: QA/Review_
  - [ ] Analysis of Intrument tests, abd performing manual testing (end-to-end, based on story testing/AC) on each client platform. 
  - [ ] Documentation of Testresults and make necessary actions based on that (adjustments, fixes, etc) until its considered as Done and no adjustments needed
  - [ ] Iteration tasks based on the QA result
  - [ ] Review with Stakeholders, Presenting the Result (Done Story) and get the fbks
  - [ ] Final adjustments if needed
  - [ ] Deployment and Release management 
  - [ ] Self-diagnostics, "retrospective": rate of process and result
